name: Run Trade Action

on:
  schedule:
    - cron: '55 0/1 * * *' # 2000 available minutes per month, 2 min/day for logging, leaves 62 min/day for trading.timezone
    # expected 2 minutes setup per run then 5 minutes for execution would allow for trade action to run every 3 hours, this 
    # could be reduced if we can optimize the requirements for running, if we could scale total run execution to 5 minutes we
    # can run every 2 hours with around 12 second margin for each run.
  workflow_dispatch: # Manual trigger

jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "requirements-trade.txt"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: uv pip install --system -r requirements-trade.txt

      - name: Create Data directory
        run: mkdir -p Data

      - name: Run trader
        env:
          KALSHI_ACCESS_KEY: ${{ secrets.KALSHI_ACCESS_KEY }}
          KALSHI_RSA_PRIVATE_KEY: ${{ secrets.KALSHI_RSA_PRIVATE_KEY }}
          POLYMARKET_WALLET_ADDRESS: ${{ secrets.POLYMARKET_WALLET_ADDRESS }}
          POLY_FUNDER_ADDRESS: ${{ secrets.POLY_FUNDER_ADDRESS }}
          POLY_PRIVATE_KEY: ${{ secrets.POLY_PRIVATE_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python src/execution/portfolio_arb_monitor.py --live # <---The file we intend to run
